//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minvu.Notificaciones.IData.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADJUNTO
    {
        public int IDADJUNTO { get; set; }
        public Nullable<int> IDENVIO { get; set; }
        public string RUTA { get; set; }
        public string NOMBRE { get; set; }
        public Nullable<int> TAMANIO { get; set; }
    
        public virtual ENVIO ENVIO { get; set; }
    }
}
