//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minvu.Notificaciones.IData.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class CORREO
    {
        public int IDCORREO { get; set; }
        public Nullable<int> IDESTADOCORREO { get; set; }
        public Nullable<int> IDDESTINATARIO { get; set; }
        public Nullable<int> IDENVIO { get; set; }
        public Nullable<int> IDSISTEMAEMISOR { get; set; }
        public string ASUNTO { get; set; }
        public string CUERPO { get; set; }
        public string CUERPOVISUALIZACION { get; set; }
        public Nullable<System.DateTime> FECHAHORA { get; set; }
    
        public virtual SISTEMA_EMISOR SISTEMA_EMISOR { get; set; }
        public virtual DESTINATARIO DESTINATARIO { get; set; }
        public virtual ENVIO ENVIO { get; set; }
        public virtual ESTADO_CORREO ESTADO_CORREO { get; set; }
    }
}
