//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minvu.Notificaciones.IData.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class DESTINATARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DESTINATARIO()
        {
            this.CORREO = new HashSet<CORREO>();
        }
    
        public int IDDESTINATARIO { get; set; }
        public string CASILLACORREO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CORREO> CORREO { get; set; }
    }
}
