//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minvu.Notificaciones.IData.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENVIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ENVIO()
        {
            this.ADJUNTO = new HashSet<ADJUNTO>();
            this.CORREO = new HashSet<CORREO>();
        }
    
        public int IDENVIO { get; set; }
        public string IDUSUARIO { get; set; }
        public Nullable<int> IDPLANTILLACORREO { get; set; }
        public Nullable<int> IDESTADOENVIO { get; set; }
        public Nullable<System.DateTime> FECHAHORA { get; set; }
        public string CONCOPIA { get; set; }
        public string CONCOPIAOCULTA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ADJUNTO> ADJUNTO { get; set; }
        public virtual ESTADO_ENVIO ESTADO_ENVIO { get; set; }
        public virtual PLANTILLA_CORREO PLANTILLA_CORREO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CORREO> CORREO { get; set; }
    }
}
