//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minvu.Notificaciones.IData.ORM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NotificacionesEntities : DbContext
    {
        public NotificacionesEntities()
            : base("name=NotificacionesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADJUNTO> ADJUNTO { get; set; }
        public virtual DbSet<DESTINATARIO> DESTINATARIO { get; set; }
        public virtual DbSet<ENVIO> ENVIO { get; set; }
        public virtual DbSet<ESTADO_CORREO> ESTADO_CORREO { get; set; }
        public virtual DbSet<ESTADO_ENVIO> ESTADO_ENVIO { get; set; }
        public virtual DbSet<ESTADO_PLANTILLA_CORREO> ESTADO_PLANTILLA_CORREO { get; set; }
        public virtual DbSet<EVENTO> EVENTO { get; set; }
        public virtual DbSet<NOTIFICACION> NOTIFICACION { get; set; }
        public virtual DbSet<PALABRAS_PROHIBIDAS> PALABRAS_PROHIBIDAS { get; set; }
        public virtual DbSet<PLANTILLA_CORREO> PLANTILLA_CORREO { get; set; }
        public virtual DbSet<SISTEMA_EMISOR> SISTEMA_EMISOR { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
        public virtual DbSet<MENSAJE> MENSAJE { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<CORREO> CORREO { get; set; }
    }
}
