//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minvu.Notificaciones.IData.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class PALABRAS_PROHIBIDAS
    {
        public int IDPALABRAPROHIBIDA { get; set; }
        public string IDUSUARIO { get; set; }
        public string PALABRA { get; set; }
        public Nullable<System.DateTime> FECHAINGRESO { get; set; }
        public string IDUSUARIOMODIFICACION { get; set; }
        public Nullable<System.DateTime> FECHAMODIFICACION { get; set; }
        public Nullable<bool> ESTADOVIGENCIA { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
    }
}
