//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minvu.Notificaciones.IData.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLANTILLA_CORREO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PLANTILLA_CORREO()
        {
            this.ENVIO = new HashSet<ENVIO>();
        }
    
        public int IDPLANTILLACORREO { get; set; }
        public Nullable<int> IDESTADOPLANTILLACORREO { get; set; }
        public string IDUSUARIO { get; set; }
        public string NOMBRE { get; set; }
        public string ASUNTO { get; set; }
        public string CUERPO { get; set; }
        public Nullable<System.DateTime> FECHACREACION { get; set; }
        public Nullable<int> IDSISTEMAEMISOR { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ENVIO> ENVIO { get; set; }
        public virtual ESTADO_PLANTILLA_CORREO ESTADO_PLANTILLA_CORREO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        public virtual SISTEMA_EMISOR SISTEMA_EMISOR { get; set; }
    }
}
