//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Minvu.Notificaciones.IData.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class SISTEMA_EMISOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SISTEMA_EMISOR()
        {
            this.NOTIFICACION = new HashSet<NOTIFICACION>();
            this.PLANTILLA_CORREO = new HashSet<PLANTILLA_CORREO>();
            this.CORREO = new HashSet<CORREO>();
        }
    
        public int IDSISTEMAEMISOR { get; set; }
        public string CASILLACORREO { get; set; }
        public string NOMBRESISTEMA { get; set; }
        public Nullable<bool> VIGENTE { get; set; }
        public string TAREAPSSIM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NOTIFICACION> NOTIFICACION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PLANTILLA_CORREO> PLANTILLA_CORREO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CORREO> CORREO { get; set; }
    }
}
